version: '3.8'

services:
  frontend:
    container_name: contextual-rag-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - crag-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: contextual-rag-backend
    ports:
      - "8000:8000"
      - "6006:6006"
    volumes:
      - app_data:/workspace/backend/data
      - ./backend:/workspace/backend
    depends_on:
      ollama:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - crag-net
  
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]  # Better endpoint
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s  # Extra time for initial startup
    restart: unless-stopped
    networks:
      - crag-net

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: vectoruser
      POSTGRES_PASSWORD: vectorpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vectoruser -d vectordb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - crag-net
  
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile.webui
    container_name: open-webui
    ports:
      - "5000:8080"
    volumes:
      - openwebui_uploads:/app/uploads
    environment:
      OPENAI_API_BASE: "http://open-webui-pipelines:9099"
      OPENAI_API_KEY: "0p3n-w3bu!"
      OPENAI_API_TYPE: "openai"
    depends_on:
      - pipelines
    restart: unless-stopped
    networks:
      - crag-net

  pipelines:
    build:
      context: .
      dockerfile: Dockerfile.pipelines
    container_name: open-webui-pipelines
    volumes:
      - ./pipelines:/app/pipelines
    ports:
      - "9099:9099"
    environment:
      - PIPELINES_API_KEY=0p3n-w3bu!
    networks:
      - crag-net

volumes:
  app_data:
  ollama_data:
  postgres_data:
  openwebui_uploads:

networks:
  crag-net:
    driver: bridge